version: '3.11'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:8777"
      - "8000:8000"
    volumes:
      - ./backend/models:/app/backend/models
      - ./backend/datasets:/app/backend/datasets
