version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8777:8777"
      - "8000:8000"
    volumes:
      - ./backend/models:/app/backend/models
      - ./backend/datasets:/app/backend/datasets
