import type { TimelineEntry } from './types';

/**
 * About Me timeline content.
 *
 * To add an item: append an object (unique `id`), drop an image in
 * `frontend/public/about-me/`, and point `image.src` at it.
 * The page sorts newest-first by `endYear`, an `endYear` is set,
 * otherwise by `startYear`. For current job, `'present'` can be set as the `endYear`.
 */
export const TIMELINE: TimelineEntry[] = [
  {
    id: 'nobleai',
    kind: 'work',
    year: '2024–present',
    startYear: 2024,
    endYear: 'present',
    title: 'Senior Solutions Engineer',
    org: 'NobleAI',
    summary: 'Custom ML solutions, de novo molecular design, & synthetic demo generation',
    body: 'I build and deploy proof-of-value ML applications on AWS and Azure — for existing customers, pre-sales demos, and internal research into new markets. I own the path from incomplete industrial data through EDA and model tuning, and I work with Product on the NobleVIP roadmap, including a self-serve Model Builder and an agentic data-synthesis capability.',
    download: {
      href: '/about-me/C_EN-whitepaper.pdf',
      label: 'Download white paper (PDF)',
    },
    highlights: [
      'Led a de novo molecular-design program for flame retardants in low-loss semiconductor and EV uses — about $1.25–1.75M in estimated customer value, 2–3 years of R&D time saved, and 3 patent applications for the customer on new FR chemistries',
      'Shipped a synthetic-data app (React / TypeScript + FastAPI) that cut demo-dataset turnaround ~5× for the Solutions team',
      'Technical lead across $1.34M ARR, including shelf-life forecasting for a top-10 packaged-foods company',
    ],
    image: {
      src: '/about-me/C_EN-whitepaper-cover.png',
      alt: 'Cover of the C&EN white paper on practical AI in chemistry and materials R&D',
      caption: 'C&EN Whitepaper',
      fit: 'contain',
    },
  },
  {
    id: 'citrine',
    kind: 'work',
    year: '2021–2024',
    startYear: 2021,
    endYear: 2024,
    title: 'Senior Data Scientist',
    org: 'Citrine Informatics',
    summary: 'Materials informatics, active learning, & model explainability tools',
    body: 'I was the technical owner on materials-informatics contracts — from experimental design through executive readouts that won renewals and expansions. I also stood up internal research (active-learning benchmarks, structurally constrained generative design) and a lightweight Dash app for model performance and explainability, and advised lab scientists and R&D leaders on adopting ML.',
    download: {
      href: '/about-me/semiconductor-case-study.pdf',
      label: 'Download semiconductor case study (PDF)',
    },
    highlights: [
      'Drove technical success across ~$2M ARR of customer contracts',
      {
        label:
          'Lead technical contributor on three photoresist Pareto-frontier breakthroughs via active learning, including a 20% drop in lithography roughness versus the customer’s prior best',
        href: 'https://citrine.io/better-than-traditional-methods/',
      },
      'Led the data-science team’s interactive visualization suite for model QA and explainability',
    ],
    image: {
      src: '/about-me/semiconductor-case-study-cover.png',
      alt: 'Cover of the Citrine Informatics case study on AI for photolithography formulation optimization',
      caption: 'Semiconductor case study — click to download',
      fit: 'contain',
    },
  },
  {
    id: 'patent-carbon-bonded-composite',
    kind: 'patent',
    year: '2023',
    startYear: 2023,
    title: 'A method of making a three-dimensional printed carbon-bonded composite article',
    org: 'USPTO · US 2023/0399520 A1',
    href: 'https://patents.google.com/patent/US20230399520A1/en',
    summary: 'Patent #3: 3D-printed carbon-bonded composites',
    body: 'Published December 2023. This Arkema application covers a method for making a 3D-printed carbon-bonded composite article — part of the photopolymer and composite printing work I did in Sartomer technical service. I am a co-inventor on a team of nine.',
    image: {
      src: '/about-me/us-2023-0399520-cover.png',
      alt: 'First page of U.S. patent application US 2023/0399520 A1',
      caption: 'US 2023/0399520 A1',
      fit: 'contain',
    },
  },
  {
    id: 'patent-glycerol-carbonate',
    kind: 'patent',
    year: '2022',
    startYear: 2022,
    title: 'Method of making glycerol carbonate (meth)acrylate and curable compositions based thereon',
    org: 'USPTO · US 2022/0298131 A1',
    href: 'https://patents.google.com/patent/US20220298131A1/en',
    summary: 'Patent #2: Glycerol carbonate (meth)acrylate in UV-curable compositions',
    body: 'Published September 2022. Co-invented with S. Nunez. The application describes a route to glycerol carbonate (meth)acrylate and curable compositions built on that monomer — chemistry aimed at 3D-printable and other light-curable resin systems for best-in-class performance.',
    image: {
      src: '/about-me/us-2022-0298131-cover.png',
      alt: 'First page of U.S. patent application US 2022/0298131 A1',
      caption: 'US 2022/0298131 A1',
      fit: 'contain',
    },
  },
  {
    id: 'patent-light-curable-composites',
    kind: 'patent',
    year: '2022',
    startYear: 2022,
    title: 'Light-curable compositions useful for forming composite materials',
    org: 'USPTO · US 2022/0213245 A1',
    href: 'https://patents.google.com/patent/US20220213245A1/en',
    summary: 'Patent #1: Cyanoacrylates for UV 3D printed carbon fiber composites',
    body: 'Patent published July 2022; granted June 10, 2025 as U.S. Patent 12,325,768. Co-invented with W. Wolf. The application covers light-curable cyanoacrylate compositions for forming composite materials — the formulation side of the carbon-fiber and photopolymer printing work at Arkema.',
    image: {
      src: '/about-me/us-2022-0213245-cover.png',
      alt: 'First page of U.S. patent application US 2022/0213245 A1',
      caption: 'US 2022/0213245 A1',
      fit: 'contain',
    },
  },
  {
    id: 'arkema-sartomer',
    kind: 'work',
    year: '2018–2021',
    startYear: 2018,
    endYear: 2021,
    title: '3D Printing Technical Service Engineer',
    org: 'Arkema Inc. (Sartomer)',
    location: 'Exton, PA',
    summary: 'Photopolymer 3D printing, structure–property ML, & application engineering',
    body: 'I sat between formulation chemistry and customers: designing high-performance 3D-printable photopolymers to compete with engineering plastics, and building a structure–property ML system that predicted mechanical, thermal, and rheological behavior from composition and process settings. I was technical lead on polymer materials for a carbon-fiber composite printing method aimed at aerospace, automotive, and energy parts, and I helped stand up data-management standards for the group’s formulation and property databases.',
    highlights: [
      'ML system for resin performance from chemistry and processing conditions',
      'Technical lead on carbon-fiber composite 3D-printing materials',
      'Contributing inventor on three U.S. patent applications',
    ],
    image: {
      src: '/about-me/lab.svg',
      alt: 'Abstract laboratory bench with flasks and a monitor',
    },
  },
  {
    id: 'ammonia-syngas-paper',
    kind: 'publication',
    year: '2017',
    startYear: 2017,
    title: 'Thermochemical synthesis of ammonia and syngas from natural gas at atmospheric pressure',
    org: 'Industrial & Engineering Chemistry Research',
    href: 'https://pubs.acs.org/iecred/article-abstract/56/47/14014/867703/Thermochemical-Synthesis-of-Ammonia-and-Syngas?redirectedFrom=PDF',
    summary: 'Paper #3: Atmospheric-pressure route to ammonia and syngas',
    body: 'M.G. Heidlage, E.A. Kezar, K.C. Snow, P.H. Pfromm. Ind. Eng. Chem. Res. 2017, 56, 47, 14014–14024. Work from the University of Minnesota on making ammonia and syngas from natural gas without the usual high-pressure loop.',
    highlights: [
      'Ind. Eng. Chem. Res. 2017, 56, 47, 14014–14024',
      'Co-author with Heidlage, Kezar, and Pfromm',
      'University of Minnesota',
    ],
    image: {
      src: '/about-me/journal.svg',
      alt: 'Stacked journal pages',
    },
  },
  {
    id: 'arkema-ehs',
    kind: 'work',
    year: '2016–2018',
    startYear: 2016,
    endYear: 2018,
    title: 'Environmental, Health, & Safety Engineer',
    org: 'Arkema Inc. (Hydrogen Peroxides)',
    location: 'Blooming Prairie, MN',
    summary: 'EHS, wastewater, and chemical manufacturing',
    body: 'First industry role after graduate school: I owned environmental compliance for the hydrogen peroxide plant — wastewater-treatment performance, troubleshooting, and state and federal permits — and project-managed capital work including tank-farm secondary containment, storm-water piping, and waste-minimization projects.',
    highlights: [
      'Environmental compliance and permit performance for plant operations',
      'Wastewater treatment monitoring and troubleshooting',
      'Capital projects: containment, storm water, and waste minimization',
    ],
    image: {
      src: '/about-me/campus.svg',
      alt: 'Stylized industrial buildings',
    },
  },
  {
    id: 'ms-umn',
    kind: 'education',
    year: '2016',
    startYear: 2016,
    title: 'M.S., Chemical Engineering',
    org: 'University of Minnesota',
    location: 'Minneapolis, MN',
    summary: 'M.S. Chemical Engineering, University of Minnesota',
    body: 'Master’s in chemical engineering at the University of Minnesota–Twin Cities. The ammonia and syngas publication sits next to this stretch of the timeline.',
    image: {
      src: '/about-me/umn-logo.svg',
      alt: 'University of Minnesota Block M logo',
      fit: 'contain',
      padded: true,
    },
  },
  {
    id: 'hbn-paper',
    kind: 'publication',
    year: '2014',
    startYear: 2014,
    title: 'Optimization of Ni–Cr flux growth for hexagonal boron nitride single crystals',
    org: 'Journal of Crystal Growth',
    href: 'https://www.sciencedirect.com/science/article/abs/pii/S0022024813006313',
    summary: 'Paper #2: Flux-growth optimization for boron nitride crystals.',
    body: 'T.B. Hoffman, B. Clubine, Y. Zhang, K. Snow, J.H. Edgar. Journal of Crystal Growth 2014, 393, 114–118. Crystal-growth work on hexagonal boron nitride from a Ni–Cr flux, from the Kansas State years.',
    highlights: [
      'J. Crystal Growth 2014, 393, 114–118',
      'Co-author with Hoffman, Clubine, Zhang, and Edgar',
      'Kansas State University',
    ],
    image: {
      src: '/about-me/journal.svg',
      alt: 'Stacked journal pages and a citation mark',
    },
  },
  {
    id: 'bs-ksu',
    kind: 'education',
    year: '2014',
    startYear: 2014,
    title: 'B.S., Chemical Engineering',
    org: 'Kansas State University',
    location: 'Manhattan, KS',
    summary: 'B.S. Chemical Engineering, Kansas State University (summa cum laude)',
    body: 'Bachelor’s in chemical engineering at Kansas State University.',
    highlights: ['Graduated summa cum laude', 'Honorable Mention - Goldwater Scholarship'],
    image: {
      src: '/about-me/kansas-state.svg',
      alt: 'Kansas State University wordmark',
      fit: 'contain',
      padded: true,
      background: '#512888',
    },
  },
  {
    id: 'nanocrystals-paper',
    kind: 'publication',
    year: '2013',
    startYear: 2013,
    title: 'A simple and generic approach for synthesizing colloidal metal and metal oxide nanocrystals',
    org: 'Nanoscale',
    href: 'https://pubs.rsc.org/nr/article-abstract/5/16/7368/407558/A-simple-and-generic-approach-for-synthesizing?redirectedFrom=fulltext',
    summary: 'Paper #1: Synthesis of colloidal metal & metal-oxide nanoparticles',
    body: 'J.E. Cloud, T.S. Yoder, N.K. Harvey, K. Snow, Y. Yang. Nanoscale 2013, 5, 7368–7378. A short, general synthesis method for colloidal metal and metal-oxide nanocrystals.',
    highlights: [
      'Nanoscale 2013, 5, 7368–7378',
      'Co-author with Cloud, Yoder, Harvey, and Yang',
    ],
    image: {
      src: '/about-me/journal.svg',
      alt: 'Stacked journal pages',
    },
  },
];
