apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservice.name }}-config
  namespace: {{ .Values.microservice.namespace }}
data:
  CHAT_PROVIDER: {{ .Values.env.CHAT_PROVIDER | quote }}
  CHAT_MODEL: {{ .Values.env.CHAT_MODEL | quote }}
  LANGSMITH_TRACING: {{ .Values.env.LANGSMITH_TRACING | quote }}
  POSTGRES_HOST: {{ .Values.env.POSTGRES_HOST }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | quote }}
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB }}
