apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
data:
  # each line is written this way to stop and print a message to the user, calling out the need to replace the empty strings from `values.yaml` with the real values, if any of the keys are missing or left as an empty string.
  POSTGRES_USER: {{ required "set secrets.POSTGRES_USER (use values.local.yaml)" .Values.secrets.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ required "set secrets.POSTGRES_PASSWORD (use values.local.yaml)" .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  GROQ_API_KEY: {{ required "set secrets.GROQ_API_KEY (use values.local.yaml)" .Values.secrets.GROQ_API_KEY | b64enc }}
  OPENAI_API_KEY: {{ required "set secrets.OPENAI_API_KEY (use values.local.yaml)" .Values.secrets.OPENAI_API_KEY | b64enc }}
  LANGSMITH_API_KEY: {{ required "set secrets.LANGSMITH_API_KEY (use values.local.yaml)" .Values.secrets.LANGSMITH_API_KEY | b64enc }}
